### ISSUE TITLE
External Image Server

### ISSUE THREAD

**Issue by dbrunton** [LibraryOfCongress/chronam#101]
Review the codepath for places where images are served. Defer the requests to an external image server.

**Comment by acdha** [comment]
#210 added the ability to use a separate IIIF server

**Comment by edsu** [comment]
It's awesome to see that this is happening. If it's ok to ask, is the IIIF server part of the chronam source code, or is it an external service?

**Comment by acdha** [comment]
External, subject to change. I'm currently testing Cantaloupe (currently packaged via https://github.com/MITLibraries/docker-cantaloupe/) but one of the nice parts about this setup is that we can monitor and swap out that component without touching the rest of the app.

**Comment by acdha** [comment]
@eikeon and I have talked about testing https://github.com/uoregon-libraries/rais-image-server as well (although see https://github.com/uoregon-libraries/rais-image-server/issues/19). So far in my testing, however, Cantaloupe has been acceptable response time for uncached images, with the common times comparable to the best-case cold cache performance of the current stack using S3FS and the worst-case performance significantly better due to the ease with which it can auto-scale.

**Comment by jechols** [comment]
Glad to see this got done!  Obviously we're not using base chronam anymore, but this issue was on my radar for a very long time :)

Without chronam, we wouldn't have Open ONI, nor would RAIS exist.  If the streaming issue is a blocker for trying it out, I will find some time in the coming weeks to look closer at it, even if that time has to be mine (as opposed to scheduled work time).  Bear in mind that RAIS does handle S3 out of the box - it just isn't as smart as we would like.

**Comment by acdha** [comment]
It's not a blocker by any means — I'm prioritizing auto-scaling over minimum TTFB, which is painless, and my focus right now has just been reducing the current error rates for that path.
