### ISSUE TITLE
Adv Search Date Range Picker "Year" values are limited to 1789 when refining search results

### ISSUE THREAD

**Issue by nwy** [LibraryOfCongress/chronam#170]
To reproduce bug:
1. Click on Advanced Search Tab
2. Under "Select Years", choose second radio button for "Date Range"
3. Select any date range using the calendar date picker
4. Enter a keyword (e.g. soldier) in the first text box under "Enter Search" and click "Search"
5. On Search Results page, once again click the Advanced Search tab
6. Under "Select Years", choose second radio button for "Date Range"
7. Observe that the year options are now only limited to "1789" in the calendar date picker drop downs. All available year values should be displayed.

![adv_search_1789](https://user-images.githubusercontent.com/3063741/33034924-5f6e9d36-cdf7-11e7-983e-84c308ea85ff.png)

**Comment by johnscancella** [comment]
Chris Adams helped me look at this, adding his notes so they don't get lost

I think the problem is in this block of code: https://github.com/LibraryOfCongress/chronam/blob/2111e4641f87f13a28de5c8114d7d400b2131766/loc/static/js/main.js#L50-L51

If you look at the generated HTML on view-source https://chroniclingamerica.loc.gov/tabs id_date1 is the `<select>` for the first date so it’s value will be whatever option has the selected attribute set. When the page first loads, that’s the default (first for id_date1, last for id_date2) but after you’ve selected something the values will be the selected years.

The most straight-forward way to fix that would be to create two separate variable pairs to track the min/max possible range and the min/max selected range independently. In the web console here’s what that looks like:

```
>> $("#id_date1").val()
"1791"
>> $("#id_date2").val()
"1795"
>> $("#id_date1 option:first-child").val()
"1789"
>> $("#id_date2 option:last-child").val()
"1949"
```

It’s less useful in this case but the HTML5 APIs make this easier to do without jQuery:

```
>> document.getElementById('id_date1').value
"1791"
>> document.querySelector('#id_date1 option:first-child').value
"1789"
```
